services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:  # Port mapping
      - 8501:8501
    volumes:  # Mounting the model directory
      - .:/workspace/app
    image: 'linus/streamlit'
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # command: ["tail", "-f", "/dev/null"]
    